on: [push]

name: Tests

defaults:
  run:
    shell: bash
      
env:
  CI: true
  FORCE_COLOR: 2


jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
           submodules: recursive

      - uses: actions/setup-node@v2
      - uses: cachix/install-nix-action@v13
      - uses: cachix/cachix-action@v10
        with:
          name: dapp
        
      - name: Run tests
        id: tests-run
        run: dapp test
        # Enable this if using forking tests
        # env:
        #  ETH_RPC_URL: https://eth-mainnet.alchemyapi.io/v2/${{ secrets.ALCHEMY_API_KEY }}

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
           submodules: recursive
      - uses: actions/setup-node@v2
      - uses: cachix/install-nix-action@v13
      - uses: cachix/cachix-action@v10
        with:
          name: dapp

      - name: Build the contracts
        id: make-build
        run: dapp build

      - name: Deploy and run checks
        id: test-deploy
        run: dapp test

